--Essentials Variables

local MapLib = game.GetMapLib:Invoke()()
local Map = MapLib.map
-- PreMap Script

MapLib:SetLiquidType(Map.Special.Liquids._Liquid1, "lava")
MapLib:SetLiquidType(Map.Special.Liquids._Liquid2, "lava")
MapLib:SetLiquidType(Map.Special.Liquids._Liquid3, "lava")
MapLib:SetLiquidType(Map.Special.Liquids._Liquid4, "lava")
MapLib:SetLiquidType(Map.Special.Liquids._Liquid5, "lava")
MapLib:SetLiquidType(Map.Special.Liquids._Liquid6, "lava")
MapLib:SetLiquidType(Map.Special.Liquids._Liquid7, "lava")
MapLib:SetLiquidType(Map.Special.Liquids._Liquid8, "lava")
MapLib:SetLiquidType(Map.Special.Liquids._Liquid9, "lava")
MapLib:SetLiquidType(Map.Special.Liquids._Liquid13, "lava")
MapLib:SetLiquidType(Map.Special.Liquids._Liquid14, "lava")
MapLib:SetLiquidType(Map.Special.Liquids._Liquid15, "lava")
MapLib:SetLiquidType(Map.Special.Liquids._Liquid16, "lava")
MapLib:SetLiquidType(Map.Special.Liquids._Liquid17, "lava")
MapLib:Alert("Welcome to UnderLabs", Color3.new(1, 0, 0), 3)


--Button Events/Button Functions


MapLib:GetButtonEvent(1):Connect(function(player)
	wait(1.5)
		MapLib:MovePart(Map.Special.Moveables.LockDoor1, Vector3.new(0, 30, 0), 1.5, true)
	wait(1.5)
		MapLib:MovePart(Map.Special.Moveables.LockDoor2, Vector3.new(0, 0, 30), 1.5, true)
end)

MapLib:GetButtonEvent(2):Connect(function(player)
	wait(1.25)
		MapLib:MovePart(Map.Special.Moveables.Doors1, Vector3.new(0, 0, 15), 1, true)
		MapLib:MovePart(Map.Special.Moveables.Doors2, Vector3.new(0, 15, 0), 1, true)
		MapLib:MovePart(Map.Special.Moveables.Doors3, Vector3.new(0, -15, 0), 1, true)
		MapLib:MovePart(Map.Special.Moveables.Doors4, Vector3.new(0, 0, -15), 1, true)
end)

MapLib:GetButtonEvent(5):Connect(function(player)
		MapLib:MovePartLocal(Map.Special.Liquids._Liquid2, Vector3.new(0, -38, 0), 1.2)
		MapLib:MovePart(Map.Special.Moveables.Lock1, Vector3.new(10, 0, 0), 1, true)
		MapLib:MovePart(Map.Special.Moveables.Lock2, Vector3.new(-10, 0, 0), 1, true)
		MapLib:MovePart(Map.Special.Liquids._Liquid3, Vector3.new(0, -17, 0), 1)
	wait(1)
		MapLib:MovePart(Map.Special.Moveables.DoorLock1, Vector3.new(5, 0, 0), 0.75, true)
		MapLib:MovePart(Map.Special.Moveables.DoorLock2, Vector3.new(-5, 0, 0), 0.75, true)
		MapLib:MovePart(Map.Special.Moveables.DoorPart1, Vector3.new(-5, 0, 0), 0.75, true)
		MapLib:MovePart(Map.Special.Moveables.DoorPart2, Vector3.new(5, 0, 0), 0.75, true)
		MapLib:MovePart(Map.Special.Moveables.DoorPart3, Vector3.new(5, 0, 0), 0.75, true)
		MapLib:MovePart(Map.Special.Moveables.DoorPart4, Vector3.new(5, 0, 0), 0.75, true)
		MapLib:MovePart(Map.Special.Moveables.DoorPart5, Vector3.new(-5, 0, 0), 0.75, true)
		MapLib:MovePart(Map.Special.Moveables.DoorPart6, Vector3.new(-5, 0, 0), 0.75, true)
		MapLib:MovePart(Map.Special.Moveables.DoorPart7, Vector3.new(5, 0, 0), 0.75, true)
		MapLib:MovePart(Map.Special.Moveables.DoorPart8, Vector3.new(-5, 0, 0), 0.75, true)
		MapLib:MovePartLocal(Map.Special.Liquids._Liquid2, Vector3.new(0, -17, 0), 0.25)
end)

MapLib:GetButtonEvent(9):Connect(function(player)
	MapLib:MovePart(Map.Special.Moveables.Button9Move1, Vector3.new(5, 0, 0), 0.5, true)
	MapLib:MovePart(Map.Special.Moveables.Button9Move2, Vector3.new(5, 0, 0), 0.5, true)
	MapLib:MovePart(Map.Special.Moveables.Button9Move3, Vector3.new(5, 0, 0), 0.5, true)
	MapLib:MovePart(Map.Special.Moveables.Button9Move4, Vector3.new(5, 0, 0), 0.5, true)
	MapLib:MovePart(Map.Special.Moveables.Button9Move5, Vector3.new(5, 0, 0), 0.5, true)
	wait(1)
	MapLib:MovePart(Map.Special.Moveables.CloseableDoor, Vector3.new(0, 15, 0), 2, true)
end)

--Self Activating Scripts

wait(7.35)
	MapLib:MovePartLocal(Map.Special.Liquids._Liquid1, Vector3.new(0, 35, 0), 2.075)
	MapLib:MovePart(Map.Special.Moveables.CloseDoor1, Vector3.new(0, 20, 0), 1.35, true)
wait(2.05)
	-- T+9.60
	MapLib:MovePartLocal(Map.Special.Liquids._Liquid2, Vector3.new(0, 38, 0), 0.65)
	MapLib:MovePartLocal(Map.Special.Liquids._Liquid3, Vector3.new(0, 1, 0), 1)
wait(7)
	-- T+17.60
	MapLib:MovePart(Map.Special.Liquids._Liquid3, Vector3.new(0, 16, 0), 1)
wait(5.5)
	-- T+22.10
	MapLib:MovePartLocal(Map.Special.Liquids._Liquid3, Vector3.new(0, 30, 0), 5)
	MapLib:MovePart(Map.Special.Moveables.MoveablesBlock2, Vector3.new(0, 10, 0), 1, true)
wait(4.6)
	-- T+26.7
	MapLib:MovePart(Map.Special.Moveables.DoorMove1, Vector3.new(0, 0, 6), 0.25, true)
	MapLib:MovePart(Map.Special.Moveables.DoorMove2, Vector3.new(0, 0, 6), 0.25, true)
	MapLib:MovePart(Map.Special.Moveables.DoorMove3, Vector3.new(0, 0, 6), 0.25, true)
	MapLib:MovePart(Map.Special.Moveables.DoorMove4, Vector3.new(0, 0, 6), 0.25, true)
	MapLib:MovePart(Map.Special.Moveables.DoorMove5, Vector3.new(0, 0, 6), 0.25, true)
	MapLib:MovePart(Map.Special.Moveables.DoorMove6, Vector3.new(0, 0, 6), 0.25, true)
	MapLib:MovePart(Map.Special.Moveables.DoorMove7, Vector3.new(0, 0, 6), 0.25, true)
wait(0.5)
	-- T+28.00
	MapLib:MovePartLocal(Map.Special.Liquids._Liquid2, Vector3.new(0, 62, 0), 1)
	MapLib:MovePart(Map.Special.Moveables.MoveablesBlock1, Vector3.new(0, 9, 0), 0.1, true)
wait(2)
	-- T+30.00
	MapLib:MovePartLocal(Map.Special.Liquids._Liquid4, Vector3.new(0, 87.3, 0), 8.5)
wait(11)
	-- T+41.00
	MapLib:MovePartLocal(Map.Special.Liquids._Liquid4, Vector3.new(0, 31.5 ,0), 2.5)
wait(8.75)
	-- T+49.75
	MapLib:MovePart(Map.Special.Moveables.Part1, Vector3.new(4.4, 0, 0), 0.5, true)
	MapLib:MovePart(Map.Special.Moveables.Part2, Vector3.new(4.4, 0, 0), 0.5, true)
	MapLib:MovePart(Map.Special.Moveables.Part3, Vector3.new(4.4, 0, 0), 0.5, true)
	MapLib:MovePart(Map.Special.Moveables.Part4, Vector3.new(4.4, 0, 0), 0.5, true)
	MapLib:MovePart(Map.Special.Moveables.Part5, Vector3.new(4.4, 0, 0), 0.5, true)
wait(0.5)
MapLib:MovePartLocal(Map.Special.Liquids._Liquid4, Vector3.new(0, 40 ,0), 0.5)
wait(3.5)
	MapLib:MovePart(Map.Special.Moveables.LabDoor, Vector3.new(-10, 0, 0), 1, true)
wait(1.5)
	MapLib:MovePartLocal(Map.Special.Liquids._Liquid5, Vector3.new(0, 30, 0), 3)
	MapLib:MovePartLocal(Map.Special.Liquids._Liquid6, Vector3.new(0, 30, 0), 3)
wait(12.5)
	MapLib:MovePartLocal(Map.Special.Liquids._Liquid7, Vector3.new(0, 40, 0), 3)
	MapLib:MovePart(Map.Special.Moveables.LabBlock1, Vector3.new(0, 12, 0), 1, true)
wait(12.5)
	MapLib:MovePart(Map.Special.Moveables.MoveUpCave, Vector3.new(0, 33, 0), 2, true)
	MapLib:MovePart(Map.Special.Liquids._Liquid8, Vector3.new(0, 44, 0), 2, true)
	MapLib:MovePartLocal(Map.Special.Liquids._Liquid9, Vector3.new(0, 542, 0), 30)
wait(22)
	MapLib:MovePartLocal(Map.Special.Liquids._Liquid13, Vector3.new(0, 72, 0), 5)
	MapLib:MovePartLocal(Map.Special.Liquids._Liquid16, Vector3.new(0, 72, 0), 5)
wait(1)
	MapLib:MovePart(Map.Special.Moveables.Elevator2, Vector3.new(-5.9, 0, 0), 0.5, true)